apiVersion: apps/v1
kind: Deployment
metadata:
  name: spfbl-admin-frontend
spec:
  selector:
    matchLabels:
      app: spfbl-admin
      tier: spfbl-admin-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: spfbl-admin
        tier: spfbl-admin-frontend
    spec:
      containers:
      - name: spfbl-admin
        image: kmee/spfbl-admin:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
