apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spfbl-admin-ssl
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: spfbl-admin.kmee.dev.br
      http:
        paths:
          - path: /
            backend:
              serviceName: spfbl-admin
              servicePort: 8000
  tls:
    - hosts:
        - spfbl-admin.kmee.dev.br
      secretName: letsencrypt-prod
status:
  loadBalancer:
    ingress:
    - ip: 10.10.6.11
#    - ip: 10.10.6.12
#    - ip: 10.10.6.13
