apiVersion: v1
kind: Service
metadata:
  name: spfbl-admin-frontend
  labels:
    #app: spfbl-admin
    #tier: frontend-spfbl-admin
    cattle.io/creator: norman
spec:
  type: ClusterIP
  ports:
  - name: default
    port: 8000
  selector:
    app: spfbl-admin
    tier: spfbl-admin-frontend
